---
name: "Python Semantic Release - Publish"

description: "Publish Python Wheels and Other Artefacts to GitHub Releases"

inputs:
  root_options:
    description: |
      Additional options for the root `semantic-release` command.
      Example: -vv --noop
    required: false
    default: "-v"

  directory:
    description: |
      Sub-directory to cd into before running semantic-release publish
    default: "."
    required: false

  github_token:
    description: |
      GitHub token used to upload artefacts. Requires permission to create and
      edit releases.
    required: true

  tag:
    description: |
      The tag corresponding to the GitHub Release that the artefacts should
      be published to. Defaults to 'latest', in which case the latest tag
      will be identified by Python Semantic Release and used to publish to.
    required: false
    default: "latest"

runs:
  using: "docker"
  image: "Dockerfile"
